#include QMK_KEYBOARD_H
#include "layers.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[LAYER_BASE] = LAYOUT_split_3x6_3(LALT_T(KC_ESC), LT(5,KC_Q), KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, LCTL_T(KC_TAB), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, RALT_T(KC_QUOT), TO(2), LT(3,KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, LT(4,KC_SLSH), KC_RCTL, MO(2), LSFT_T(KC_ENT), LGUI_T(KC_SPC), KC_RSFT, KC_SPC, KC_BSPC),
	[LAYER_COLEMAK] = LAYOUT_split_3x6_3(LALT_T(KC_ESC), LT(5,KC_Q), KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSLS, LCTL_T(KC_TAB), KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, RALT_T(KC_QUOT), TO(2), LT(3,KC_Z), KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, LT(4,KC_SLSH), KC_RCTL, MO(2), LSFT_T(KC_ENT), LGUI_T(KC_SPC), KC_RSFT, KC_SPC, KC_BSPC),
	[LAYER_NUM] = LAYOUT_split_3x6_3(TO(0), KC_LBRC, KC_RBRC, KC_LPRN, KC_RPRN, KC_BSLS, KC_PSLS, KC_7, KC_8, KC_9, KC_PMNS, KC_BSPC, KC_LGUI, KC_BSPC, KC_DEL, KC_LCBR, KC_RCBR, KC_PIPE, KC_PAST, KC_4, KC_5, KC_6, KC_PPLS, KC_PEQL, TO(3), KC_GRV, KC_TILD, KC_QUOT, KC_DQUO, KC_UNDS, KC_PCMM, KC_1, KC_2, KC_3, KC_ENT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PDOT, KC_0),
	[LAYER_NAV] = LAYOUT_split_3x6_3(TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, TO(4), KC_NO, KC_LCTL, KC_LALT, KC_LGUI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[LAYER_SETTINGS] = LAYOUT_split_3x6_3(TO(0), RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, RGB_SPI, DF(0), DF(1), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD, RGB_SPD, KC_BRID, KC_NO, KC_BRIU, CMB_TOG, KC_NO, KC_NO, TO(5), RGB_RMOD, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_MUTE, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[LAYER_FUNCTIONS] = LAYOUT_split_3x6_3(TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_NO, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, TO(2), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_RCTL, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};


